services:
  haskell:
    command: sleep infinity
    container_name: haskell
    image: haskell:8
    network_mode: none
    pids_limit: 20
    read_only: true
    restart: always
    volumes:
      - ./docker/prettify.hs:/prettify.hs:ro
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: 1k
  node:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: discord_ghci_bot
    depends_on:
      - haskell
    env_file: .env
    image: ghci-bot:v1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

version: '3.8'
